import { Inter } from "next/font/google";
import "./globals.css";
import { Raleway } from "next/font/google";
import localfont from "next/font/local";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });
const raleway_init = Raleway({
  subsets:['latin'],
  weight:['100','300','400'],
  variable:"--font-raleway",
}); 

const minion = localfont({
  src:[
    {
      path:'../../public/font/Minion-Variable-Concept.otf',
      weight:'700',
    },
  ],
  variable:"--font-minion",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${minion.variable}`}>
       {/* <meta name="viewport" content="width=device-width, initial-scale=1.0" />
       <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/> */}
{/* <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"/> */}
      <body className={raleway_init.variable}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
